version: '3.8'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080" # Mapeia a porta 80 do contêiner para a 5000 no host
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=PayCraftDb;User Id=postgres;Password=07Z7rYIdS4aae1g;
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 07Z7rYIdS4aae1g
      POSTGRES_DB: PayCraftDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
